/**
 * 12-MONTH ROAD TO 24 LPA CURRICULUM DATASET
 */
export const INITIAL_ROADMAP_DATA = [
  {
    monthNumber: 1,
    title: 'Month 1: TypeScript + Professional JavaScript',
    subtitle: 'Disturbance Month — Build Habit & Core Foundations',
    objective: 'Build the habit + strengthen JavaScript/TypeScript + start your main production project.',
    weekdayTime: '45–75 min',
    weekendTime: '2 hours',
    isLighter: true,
    weeks: [
      {
        weekNumber: 1,
        title: 'Week 1: TypeScript Foundations',
        focus: 'Type system, generics, type narrowing & utility types',
        days: [
          {
            id: 'm1-w1-d1',
            dayNumber: 1,
            title: 'TypeScript vs JavaScript & Primitive Types',
            duration: '60 min',
            objective: 'Understand why TypeScript exists and convert first JS file.',
            learnItems: ['TypeScript vs JavaScript', 'Why TypeScript exists', 'Type inference', 'Primitive types'],
            buildItems: ['Convert one existing JS file in your portfolio to TS'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w1-d2',
            dayNumber: 2,
            title: 'Types, Interfaces & Unions',
            duration: '60 min',
            objective: 'Master structured types and interfaces.',
            learnItems: ['type vs interface', 'optional properties', 'readonly', 'union types'],
            buildItems: ['Create types for User, Product, Order, Address entities'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w1-d3',
            dayNumber: 3,
            title: 'Generics & Reusable Contracts',
            duration: '60 min',
            objective: 'Understand type parameters and generic contracts.',
            learnItems: ['Generics fundamentals', 'Generic functions', 'Generic interfaces'],
            buildItems: ['Build ApiResponse<T> and PaginatedResponse<T> abstractions'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w1-d4',
            dayNumber: 4,
            title: 'Advanced Types & Narrowing',
            duration: '60 min',
            objective: 'Type safety and runtime verification.',
            learnItems: ['any vs unknown vs never', 'type narrowing', 'custom type guards'],
            buildItems: ['Write 5 standalone type guard examples with runtime verification'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w1-d5',
            dayNumber: 5,
            title: 'Utility Types Deep Dive',
            duration: '60 min',
            objective: 'Master built-in TypeScript transformations.',
            learnItems: ['Partial', 'Pick', 'Omit', 'Required', 'Readonly', 'Record'],
            buildItems: ['Create an API payload transformation using Pick and Omit'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w1-sat',
            dayNumber: 'Saturday',
            title: 'Weekend Build: TypeScript API Types Library',
            duration: '2.0 hours',
            objective: 'Create a clean, shareable types library for your production project.',
            learnItems: ['Architecting modular type definitions'],
            buildItems: ['Build TypeScript API library with User, Product, Order, Pagination, API errors, API response'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w1-sun',
            dayNumber: 'Sunday',
            title: 'Weekend DSA + Project Repo Initialization',
            duration: '2.0 hours',
            objective: 'DSA problem solving + GitHub repo creation + Week 1 revision.',
            learnItems: ['Week 1 complete conceptual recall without looking'],
            buildItems: ['Create GitHub repository for your main flagship project'],
            dsaItems: ['Two Sum', 'Contains Duplicate'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 2,
        title: 'Week 2: TypeScript + Node.js Architecture',
        focus: 'Event Loop, Promises, Clean Node Server Architecture',
        days: [
          {
            id: 'm1-w2-d8',
            dayNumber: 8,
            title: 'Asynchronous JavaScript & Promises',
            duration: '60–75 min',
            objective: 'Master async control flow and error management.',
            learnItems: ['async/await internals', 'Promise mechanics', 'Promise.all vs Promise.allSettled', 'Centralized error handling'],
            buildItems: ['Write resilient concurrent API fetchers with Promise.allSettled'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w2-d9',
            dayNumber: 9,
            title: 'Node.js Event Loop Internals',
            duration: '75 min',
            objective: 'Deep understanding of execution phases in Node.js runtime.',
            learnItems: ['Call stack', 'Node.js Event Loop phases', 'Microtasks (process.nextTick, Promise)', 'Macrotasks (setImmediate, timers)'],
            buildItems: ['Trace output of 5 complex microtask/macrotask execution puzzles'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w2-d10',
            dayNumber: 10,
            title: 'Modules & Environment Configuration',
            duration: '60 min',
            objective: 'Production config management and ESM/CJS modules.',
            learnItems: ['ES Modules vs CommonJS', 'Environment variables with dotenv/zod', 'Strict configuration validation'],
            buildItems: ['Set up type-safe environment configuration parser with Zod'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w2-d11',
            dayNumber: 11,
            title: 'Node + TypeScript Clean Architecture Setup',
            duration: '75 min',
            objective: 'Initialize production folder hierarchy.',
            learnItems: ['Layered architecture pattern (Controller -> Service -> Repository)'],
            buildItems: ['Setup src/ with controllers/, services/, repositories/, routes/, middleware/, config/, utils/'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w2-d12',
            dayNumber: 12,
            title: 'REST Endpoints Implementation',
            duration: '75 min',
            objective: 'Build REST user management endpoints in TypeScript.',
            learnItems: ['REST routing conventions', 'Controller-Service data passing'],
            buildItems: ['Build GET /users, GET /users/:id, POST /users, PUT /users/:id, DELETE /users/:id'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w2-sat',
            dayNumber: 'Saturday',
            title: 'Weekend Build: Middleware & Centralized Logging',
            duration: '2.5 hours',
            objective: 'Add production middleware, validation, error handler, and logger.',
            learnItems: ['Express middleware lifecycle & error interception'],
            buildItems: ['Add validation layer, centralized error middleware, and structured logging'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w2-sun',
            dayNumber: 'Sunday',
            title: 'DSA + Senior Code Review with AI',
            duration: '2.5 hours',
            objective: 'Solve DSA anagrams and conduct architectural audit with AI.',
            learnItems: ['Prompting AI as a Staff Node.js Engineer for architectural code review'],
            buildItems: ['Prompt AI: "Review this backend architecture like a senior Node.js engineer. Don\'t rewrite it. Identify design problems and explain why they are problems."'],
            dsaItems: ['Valid Anagram', 'Group Anagrams'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 3,
        title: 'Week 3: PostgreSQL & Relational Database Engineering',
        focus: 'Schemas, Relational Joins, Indexes, ACID Transactions',
        days: [
          {
            id: 'm1-w3-d15',
            dayNumber: 15,
            title: 'Relational Database Fundamentals',
            duration: '60–75 min',
            objective: 'Transition from NoSQL mindset to relational schema design.',
            learnItems: ['Relational database design', 'Tables, primary keys, foreign keys', '1-1, 1-N, N-M relationships'],
            buildItems: ['Design relational schema for Users, Organizations, Projects, Tasks'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w3-d16',
            dayNumber: 16,
            title: 'SQL Joins & Aggregations',
            duration: '75 min',
            objective: 'Master multi-table queries and analytical aggregations.',
            learnItems: ['INNER JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'GROUP BY', 'HAVING'],
            buildItems: ['Write 10 complex SQL join and aggregation queries against relational schema'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w3-d17',
            dayNumber: 17,
            title: 'PostgreSQL Indexes & Query Planning',
            duration: '75 min',
            objective: 'Understand B-Trees and when indexes hurt performance.',
            learnItems: ['B-Tree indexes', 'Composite indexes', 'Index overhead on writes', 'When indexes hurt'],
            buildItems: ['Create index benchmarks and compare execution plans'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w3-d18',
            dayNumber: 18,
            title: 'ACID & Database Transactions',
            duration: '75 min',
            objective: 'Prevent inconsistent data in concurrent financial/order transactions.',
            learnItems: ['Atomicity, Consistency, Isolation, Durability', 'Transaction rollbacks', 'Handling: Money deducted -> Order creation fails'],
            buildItems: ['Write atomic transaction block with rollback in Node.js + SQL'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w3-d19',
            dayNumber: 19,
            title: 'Isolation Levels & Race Conditions',
            duration: '75 min',
            objective: 'Understand concurrency locks and dirty/phantom reads.',
            learnItems: ['Read Committed vs Repeatable Read vs Serializable', 'Race conditions', 'Row-level locking (SELECT FOR UPDATE)'],
            buildItems: ['Simulate a race condition and resolve it using row locking'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w3-sat',
            dayNumber: 'Saturday',
            title: 'Weekend Build: Database Schema Architecture',
            duration: '2.5 hours',
            objective: 'Implement PostgreSQL database migrations for production project.',
            learnItems: ['Database migration strategies and foreign key constraints'],
            buildItems: ['Set up PostgreSQL database with Users, Organizations, Projects, Tasks tables'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w3-sun',
            dayNumber: 'Sunday',
            title: 'DSA + 10 Complex SQL Queries',
            duration: '2.5 hours',
            objective: 'Solve DSA stack & search problems + write 10 production SQL queries.',
            learnItems: ['Binary search divide-and-conquer principles'],
            buildItems: ['Write 10 production SQL queries against project database'],
            dsaItems: ['Valid Parentheses', 'Binary Search'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 4,
        title: 'Week 4: Production API Engineering & Auth',
        focus: 'HTTP protocol, JWT rotation, RBAC, Month 1 Self-Audit',
        days: [
          {
            id: 'm1-w4-d22',
            dayNumber: 22,
            title: 'HTTP Protocol Deep Dive',
            duration: '60–75 min',
            objective: 'Understand HTTP methods and idempotency.',
            learnItems: ['HTTP specification', 'GET, POST, PUT, PATCH, DELETE', 'Idempotent vs Non-idempotent operations'],
            buildItems: ['Audit all project endpoints for strict HTTP verb conformance'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w4-d23',
            dayNumber: 23,
            title: 'Status Codes, Headers, Cookies & CORS',
            duration: '60–75 min',
            objective: 'Production network headers and security.',
            learnItems: ['2xx, 3xx, 4xx, 5xx semantics', 'Security headers (CSP, HSTS)', 'HttpOnly SameSite cookies', 'CORS preflight (OPTIONS)'],
            buildItems: ['Implement secure cookie session handler with strict CORS whitelist'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w4-d24',
            dayNumber: 24,
            title: 'Authentication Architectures',
            duration: '75 min',
            objective: 'Compare session-based auth vs stateless JWT tokens.',
            learnItems: ['Session cookies vs JWT', 'Short-lived Access Tokens (15m)', 'Long-lived Refresh Tokens (7d)', 'OAuth2 authorization flow'],
            buildItems: ['Design JWT refresh token rotation diagram and schema'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w4-d25',
            dayNumber: 25,
            title: 'Authentication Endpoints Implementation',
            duration: '75 min',
            objective: 'Build secure auth flow in Node + TypeScript.',
            learnItems: ['bcrypt password hashing (salt rounds 12)', 'Token signing & verification'],
            buildItems: ['Implement POST /auth/register, POST /auth/login, POST /auth/logout, GET /auth/me'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w4-d26',
            dayNumber: 26,
            title: 'Password Security & Request Validation',
            duration: '75 min',
            objective: 'Harden authentication against brute-force and payload injection.',
            learnItems: ['Password entropy requirements', 'Zod validation middleware', 'Rate limiting auth endpoints'],
            buildItems: ['Add strict Zod schemas and validation error formatters'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w4-sat',
            dayNumber: 'Saturday',
            title: 'Weekend Build: Role-Based Access Control (RBAC)',
            duration: '2.5 hours',
            objective: 'Implement granular authorization middleware for Admin, Manager, User roles.',
            learnItems: ['RBAC vs ABAC authorization patterns'],
            buildItems: ['Build requireRole("Admin" | "Manager" | "User") authorization guard'],
            completed: false,
            notes: '',
          },
          {
            id: 'm1-w4-sun',
            dayNumber: 'Sunday',
            title: 'Month 1 Deep Conceptual Self-Audit',
            duration: '2.5 hours',
            objective: 'Answer 8 senior engineering questions without looking up.',
            learnItems: [
              '1. What is Node\'s event loop and how do microtasks work?',
              '2. Why TypeScript in production?',
              '3. What is a database transaction and ACID?',
              '4. Why indexes and when do they hurt?',
              '5. JWT vs Session?',
              '6. Authentication vs Authorization?',
              '7. What happens when an API request reaches Node?',
              '8. What happens when SQL executes on database engine?',
            ],
            buildItems: ['Write private reflection notes for any gaps identified in the 8 questions'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 2,
    title: 'Month 2: Backend Engineering & Production Architecture',
    subtitle: 'From Making APIs to Operating Resilient Backend Systems',
    objective: 'Stop being someone who can "make APIs." Become someone who understands how APIs behave under load.',
    weekdayTime: '75–90 min',
    weekendTime: '2.5–3 hours',
    weeks: [
      {
        weekNumber: 5,
        title: 'Week 5: Clean Backend Architecture',
        focus: 'Controller -> Service -> Repository, Dependency Injection, Zod DTOs',
        days: [
          {
            id: 'm2-w5-d29',
            dayNumber: 29,
            title: 'Controller -> Service -> Repository Pattern',
            duration: '75 min',
            objective: 'Decouple HTTP logic, business rules, and database queries.',
            learnItems: ['Separation of concerns', 'Why Controllers should have 0 business logic', 'Why Repositories isolate ORM/SQL queries'],
            buildItems: ['Refactor 2 API modules into clean Controller -> Service -> Repository tiers'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w5-d30',
            dayNumber: 30,
            title: 'Dependency Injection Fundamentals',
            duration: '75 min',
            objective: 'Learn testable software design with inversion of control.',
            learnItems: ['Dependency Inversion Principle', 'Constructor injection', 'Mocking database layers in tests'],
            buildItems: ['Implement constructor-based service injection for user management'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w5-d31',
            dayNumber: 31,
            title: 'Centralized Error Handling Architecture',
            duration: '75 min',
            objective: 'Build custom error hierarchy with AppError, NotFoundError, UnauthorizedError.',
            learnItems: ['Operational errors vs Programmer bugs', 'Custom Error classes inheriting Error'],
            buildItems: ['Create custom error classes with HTTP status codes and error middleware'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w5-d32',
            dayNumber: 32,
            title: 'Schema Validation with Zod',
            duration: '75 min',
            objective: 'Strict request payload and query parameter validation.',
            learnItems: ['Zod schema inference', 'Custom validators and error transformations'],
            buildItems: ['Write generic validateRequest(schema) middleware'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w5-d33',
            dayNumber: 33,
            title: 'DTOs (Data Transfer Objects)',
            duration: '75 min',
            objective: 'Master Request -> Validation -> DTO -> Service -> Response pipeline.',
            learnItems: ['DTO pattern', 'Excluding sensitive fields (passwords, tokens) from responses'],
            buildItems: ['Create UserResponseDTO and TaskResponseDTO mappers'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w5-weekend',
            dayNumber: 'Weekend',
            title: 'Full Architecture Refactor of Flagship Project',
            duration: '3.0 hours',
            objective: 'Refactor complete project into Controller, Service, Repository, Database layers.',
            learnItems: ['Reviewing architecture against senior standards'],
            buildItems: ['Complete codebase reorganization and manual route verification'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 6,
        title: 'Week 6: Authentication Security & Vulnerability Auditing',
        focus: 'SQL Injection, XSS, CSRF, Rate Limiting, Threat Modeling',
        days: [
          {
            id: 'm2-w6-d36',
            dayNumber: 36,
            title: 'Password Security & Salting Internals',
            duration: '75 min',
            objective: 'Master cryptographic hashing algorithms and timing attack prevention.',
            learnItems: ['bcrypt / Argon2 hashing', 'Salt generation', 'Constant-time comparison'],
            buildItems: ['Implement password strength verification and hashing utility'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w6-d37',
            dayNumber: 37,
            title: 'JWT Security Best Practices',
            duration: '75 min',
            objective: 'Prevent JWT hijacking, "none" algorithm exploit, and replay attacks.',
            learnItems: ['JWT header injection risks', 'Signature validation', 'Blacklisting revoked tokens'],
            buildItems: ['Add token blacklist checking to auth middleware'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w6-d38',
            dayNumber: 38,
            title: 'Silent Refresh Token Rotation with Redis',
            duration: '75 min',
            objective: 'Build enterprise-grade token rotation with reuse detection.',
            learnItems: ['Token family tracking', 'Invalidating entire family upon token reuse anomaly'],
            buildItems: ['Implement token family revocation logic in auth service'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w6-d39',
            dayNumber: 39,
            title: 'Granular Role-Based Access Control',
            duration: '75 min',
            objective: 'Build permission-level authorization.',
            learnItems: ['Role vs Permission mapping', 'Dynamic resource ownership validation (userId === item.ownerId)'],
            buildItems: ['Build requireOwnershipOrAdmin middleware'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w6-d40',
            dayNumber: 40,
            title: 'OWASP Top 10 API Security',
            duration: '75 min',
            objective: 'Protect against SQL Injection, XSS, CSRF, and CORS exploits.',
            learnItems: ['Parameterized SQL queries', 'Helmet security headers', 'CORS origin validation'],
            buildItems: ['Add Helmet, sanitize user input, configure strict CORS'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w6-weekend',
            dayNumber: 'Weekend',
            title: 'Security Threat Audit: "How could someone attack this API?"',
            duration: '3.0 hours',
            objective: 'Conduct aggressive penetration test and audit of your API endpoints.',
            learnItems: ['Security audit methodologies and threat modeling'],
            buildItems: ['Document vulnerability audit report for your flagship backend'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 7,
        title: 'Week 7: Redis Caching & Rate Limiting',
        focus: 'In-memory caching, Cache-Aside Pattern, TTL, Redis Rate Limiter',
        days: [
          {
            id: 'm2-w7-d43',
            dayNumber: 43,
            title: 'Redis Fundamentals & Data Structures',
            duration: '75 min',
            objective: 'Understand in-memory caching and Redis data types (Strings, Hashes, Sets).',
            learnItems: ['Redis memory architecture', 'Key-Value strings', 'Hashes and Sorted Sets'],
            buildItems: ['Setup local Redis instance with Docker and connect ioredis client'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w7-d44',
            dayNumber: 44,
            title: 'Caching Strategies & Cache-Aside Pattern',
            duration: '75 min',
            objective: 'Master Cache-Aside, Write-Through, and Cache Invalidation.',
            learnItems: ['Cache-Aside pattern', 'Cache hit vs Cache miss', 'Cache invalidation on updates'],
            buildItems: ['Implement Cache-Aside wrapper function with generic typing'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w7-d45',
            dayNumber: 45,
            title: 'Cache Invalidation & Stampede Mitigation',
            duration: '75 min',
            objective: 'Handle cache expiration spikes and race conditions.',
            learnItems: ['TTL strategies', 'Cache stampede (Thundering herd)', 'Randomized jitter TTL'],
            buildItems: ['Add randomized TTL jitter to cached queries'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w7-d46',
            dayNumber: 46,
            title: 'Redis-Based Rate Limiting',
            duration: '75 min',
            objective: 'Implement sliding window / token bucket rate limiter.',
            learnItems: ['Fixed window vs Sliding window rate limiting', 'Redis INCR and EXPIRE'],
            buildItems: ['Build custom Redis sliding window rate limiter middleware (100 req/min)'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w7-d47',
            dayNumber: 47,
            title: 'Benchmarking: Cache vs Database Latency',
            duration: '75 min',
            objective: 'Measure and log performance improvements with caching.',
            learnItems: ['Latency metrics (p50, p95, p99)', 'Measuring TTFB and database load reduction'],
            buildItems: ['Benchmark expensive endpoint with and without Redis caching (log ms response times)'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w7-weekend',
            dayNumber: 'Weekend',
            title: 'Production Caching Integration & Latency Report',
            duration: '3.0 hours',
            objective: 'Add Redis cache to top 3 read-heavy APIs and generate performance comparison report.',
            learnItems: ['Reviewing cache hit ratios'],
            buildItems: ['Integrate Redis caching across projects and write latency benchmark document'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 8,
        title: 'Week 8: Asynchronous Message Queues & Background Workers',
        focus: 'BullMQ, Background Workers, Retries, Dead-Letter Queues, Idempotency',
        days: [
          {
            id: 'm2-w8-d50',
            dayNumber: 50,
            title: 'Asynchronous Processing & Message Queues',
            duration: '75 min',
            objective: 'Offload heavy computations and emails from HTTP response cycle.',
            learnItems: ['Why queues prevent API blocking', 'Producer-Consumer pattern', 'BullMQ architecture on Redis'],
            buildItems: ['Setup BullMQ queue and worker process in TypeScript'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w8-d51',
            dayNumber: 51,
            title: 'Background Job Retries & Exponential Backoff',
            duration: '75 min',
            objective: 'Handle external API/email failures gracefully.',
            learnItems: ['Retry attempts', 'Exponential backoff with jitter', 'Handling transient network failures'],
            buildItems: ['Configure 5 retries with exponential backoff on email jobs'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w8-d52',
            dayNumber: 52,
            title: 'Dead-Letter Queues & Failure Telemetry',
            duration: '75 min',
            objective: 'Capture permanently failed jobs for debugging.',
            learnItems: ['Dead-letter queues (DLQ)', 'Failed job logging and alerting'],
            buildItems: ['Build DLQ listener that logs fatal job errors to database'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w8-d53',
            dayNumber: 53,
            title: 'Idempotency in Distributed Processing',
            duration: '75 min',
            objective: 'Ensure duplicate job execution never causes double payments or duplicate records.',
            learnItems: ['Idempotency keys', 'Deduplication using Redis locks'],
            buildItems: ['Implement idempotency key validation on background worker'],
            completed: false,
            notes: '',
          },
          {
            id: 'm2-w8-weekend',
            dayNumber: 'Weekend',
            title: 'End-to-End Async Pipeline: API -> Queue -> Worker -> Email/Report',
            duration: '3.0 hours',
            objective: 'Build complete asynchronous pipeline for report generation or transactional email.',
            learnItems: ['End-to-end async job verification'],
            buildItems: ['Build API -> BullMQ -> Worker -> PDF/Email delivery flow'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 3,
    title: 'Month 3: PostgreSQL Deep Dive & 1M Dataset Performance',
    subtitle: 'Understanding Query Execution, Index Optimization & Profiling',
    objective: 'Understand why systems become slow and how to optimize queries on large datasets.',
    weekdayTime: '75–90 min',
    weekendTime: '3.0 hours',
    weeks: [
      {
        weekNumber: 9,
        title: 'Week 9: Query Profiling with EXPLAIN ANALYZE',
        focus: 'Query planning, Sequential Scans vs Index Scans, Buffer Cache',
        days: [
          {
            id: 'm3-w9-d57',
            dayNumber: 57,
            title: 'Reading PostgreSQL Query Execution Plans',
            duration: '75 min',
            objective: 'Master EXPLAIN (ANALYZE, BUFFERS, VERBOSE).',
            learnItems: ['Cost estimation (startup vs total)', 'Seq Scan vs Index Scan vs Index Only Scan', 'Bitmap Heap Scan'],
            buildItems: ['Run EXPLAIN ANALYZE on 5 complex queries and annotate bottlenecks'],
            completed: false,
            notes: '',
          },
          {
            id: 'm3-w9-d58',
            dayNumber: 58,
            title: 'Large Dataset Seeding (1 Million Rows)',
            duration: '75 min',
            objective: 'Generate 1,000,000 realistic records for query stress testing.',
            learnItems: ['Batch insertion strategies', 'generate_series in SQL for high-speed generation'],
            buildItems: ['Seed PostgreSQL table with 1,000,000 products/orders'],
            completed: false,
            notes: '',
          },
          {
            id: 'm3-w9-weekend',
            dayNumber: 'Weekend',
            title: 'Performance Challenge: Fix 2-Second Query on 1M Rows',
            duration: '3.0 hours',
            objective: 'Investigate why multi-filter search takes 2 seconds and reduce latency to <15ms with composite indexes.',
            learnItems: ['Index selectivity and multi-column ordering'],
            buildItems: ['Optimize 1M row search query from 2,100ms down to 12ms'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 10,
        title: 'Week 10: Advanced Pagination & Connection Pooling',
        focus: 'Offset vs Cursor Pagination, PgBouncer, Connection Pool Tuning',
        days: [
          {
            id: 'm3-w10-d64',
            dayNumber: 64,
            title: 'OFFSET Pagination vs Cursor-Based Pagination',
            duration: '75 min',
            objective: 'Understand why OFFSET 100000 kills database performance.',
            learnItems: ['OFFSET scanning overhead', 'Keyset / Cursor-based pagination (WHERE id > lastId)'],
            buildItems: ['Implement fast cursor pagination endpoint for 1M row feed'],
            completed: false,
            notes: '',
          },
          {
            id: 'm3-w10-weekend',
            dayNumber: 'Weekend',
            title: 'Connection Pooling & Database Resiliency',
            duration: '3.0 hours',
            objective: 'Configure database connection pools, idle timeouts, and graceful shutdowns.',
            learnItems: ['Connection pooling mechanics (pg pool / PgBouncer)'],
            buildItems: ['Tuning pool sizes and measuring concurrent throughput with autocannon'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 4,
    title: 'Month 4: Testing, Security, Code Quality & SOLID',
    subtitle: 'Building Enterprise Maintainability',
    objective: 'Transform your codebase into something an enterprise engineering team can reliably test and maintain.',
    weekdayTime: '75–90 min',
    weekendTime: '3.0 hours',
    weeks: [
      {
        weekNumber: 11,
        title: 'Week 11: Unit & Integration Testing (Vitest / Jest)',
        focus: 'Unit tests, Service mocks, Integration tests with Testcontainers / PostgreSQL',
        days: [
          {
            id: 'm4-w11-d71',
            dayNumber: 71,
            title: 'Unit Testing Business Logic with Vitest',
            duration: '75 min',
            objective: 'Write fast unit tests for services, utilities, and validation.',
            learnItems: ['AAA pattern (Arrange, Act, Assert)', 'Mocking repository dependencies', 'Testing edge cases and exceptions'],
            buildItems: ['Write 15 unit tests covering auth and order services with >85% coverage'],
            completed: false,
            notes: '',
          },
          {
            id: 'm4-w11-weekend',
            dayNumber: 'Weekend',
            title: 'Integration Testing: HTTP API -> Database',
            duration: '3.0 hours',
            objective: 'Test complete request lifecycle with test database.',
            learnItems: ['Integration testing with supertest and ephemeral test database'],
            buildItems: ['Write 10 integration tests validating end-to-end API flows'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 12,
        title: 'Week 12: SOLID Principles & Automated E2E Testing',
        focus: 'SOLID design principles, Playwright E2E tests, Structured Logging',
        days: [
          {
            id: 'm4-w12-d78',
            dayNumber: 78,
            title: 'SOLID Principles in TypeScript Backends',
            duration: '75 min',
            objective: 'Single Responsibility, Open-Closed, Liskov, Interface Segregation, Dependency Inversion.',
            learnItems: ['Concrete examples of each SOLID principle in Node/TypeScript'],
            buildItems: ['Refactor a coupled service to strictly adhere to Open-Closed and Dependency Inversion'],
            completed: false,
            notes: '',
          },
          {
            id: 'm4-w12-weekend',
            dayNumber: 'Weekend',
            title: 'Playwright E2E Flow & Production Code Review',
            duration: '3.0 hours',
            objective: 'Add automated browser test for login -> dashboard -> canvas flow.',
            learnItems: ['E2E testing with Playwright'],
            buildItems: ['Write Playwright test suite and setup automated npm test script'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 5,
    title: 'Month 5: Docker, Linux & Containerization',
    subtitle: 'Becoming a Production-Ready DevOps Engineer',
    objective: 'Containerize frontend, backend, PostgreSQL, and Redis so entire stack runs with docker compose up.',
    weekdayTime: '75–90 min',
    weekendTime: '3.0 hours',
    weeks: [
      {
        weekNumber: 13,
        title: 'Week 13: Linux CLI & Multi-Stage Dockerfiles',
        focus: 'Linux shell, processes, multi-stage Docker build for minimal image size',
        days: [
          {
            id: 'm5-w13-d85',
            dayNumber: 85,
            title: 'Essential Linux CLI for Backend Engineers',
            duration: '75 min',
            objective: 'Process management (ps, kill, top), permissions, logs (journalctl), networking (curl, netstat).',
            learnItems: ['Linux system commands', 'File permissions (chmod, chown)', 'Process signals (SIGTERM, SIGINT)'],
            buildItems: ['Write shell scripts for server health diagnostics and log rotation'],
            completed: false,
            notes: '',
          },
          {
            id: 'm5-w13-weekend',
            dayNumber: 'Weekend',
            title: 'Multi-Stage Production Dockerfiles',
            duration: '3.0 hours',
            objective: 'Build ultra-slim, secure Node.js production Docker images with non-root user.',
            learnItems: ['Multi-stage Docker builds', 'Docker layer caching', 'Security best practices (non-root USER node)'],
            buildItems: ['Create Dockerfile for frontend and backend reducing image size by 70%'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 14,
        title: 'Week 14: Docker Compose Orchestration',
        focus: 'Frontend + Backend + PostgreSQL + Redis local orchestration',
        days: [
          {
            id: 'm5-w14-d92',
            dayNumber: 92,
            title: 'Docker Compose Networking & Volumes',
            duration: '75 min',
            objective: 'Service discovery, persistent volumes for Postgres/Redis, health checks.',
            learnItems: ['Docker bridge networks', 'Named volumes for persistent data', 'Healthcheck dependencies (depends_on condition: service_healthy)'],
            buildItems: ['Write docker-compose.yml orchestrating Frontend, Backend, Postgres, Redis'],
            completed: false,
            notes: '',
          },
          {
            id: 'm5-w14-weekend',
            dayNumber: 'Weekend',
            title: '1-Command Production Setup Verification',
            duration: '3.0 hours',
            objective: 'Verify entire project boots with a single `docker compose up --build`.',
            learnItems: ['Container orchestration verification'],
            buildItems: ['Verify fresh clone -> docker compose up brings up full application stack with sample seed data'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 6,
    title: 'Month 6: AWS & Automated CI/CD Pipelines',
    subtitle: 'Deploying Production Full-Stack Applications with Zero Downtime',
    objective: 'Deploy to AWS (EC2, S3, RDS, CloudFront) with automated GitHub Actions CI/CD.',
    weekdayTime: '75–90 min',
    weekendTime: '3.0 hours',
    weeks: [
      {
        weekNumber: 15,
        title: 'Week 15: Core AWS Infrastructure',
        focus: 'EC2, S3, RDS, CloudFront, IAM roles & security groups',
        days: [
          {
            id: 'm6-w15-d99',
            dayNumber: 99,
            title: 'AWS Fundamentals: EC2, S3 & Security Groups',
            duration: '75 min',
            objective: 'Configure secure VPC, IAM roles, and S3 asset buckets.',
            learnItems: ['EC2 compute instances', 'S3 bucket policies and presigned URLs', 'Security group inbound/outbound rules'],
            buildItems: ['Configure S3 bucket for media uploads with presigned upload URLs'],
            completed: false,
            notes: '',
          },
          {
            id: 'm6-w15-weekend',
            dayNumber: 'Weekend',
            title: 'Deploy PostgreSQL on AWS RDS & NGINX Reverse Proxy',
            duration: '3.0 hours',
            objective: 'Set up managed database and NGINX reverse proxy with SSL.',
            learnItems: ['RDS configuration and SSL certificate provisioning via Let\'s Encrypt'],
            buildItems: ['Deploy production database on RDS and configure NGINX reverse proxy on EC2'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 16,
        title: 'Week 16: GitHub Actions CI/CD Pipeline',
        focus: 'Automated testing, Docker build, and continuous deployment on git push',
        days: [
          {
            id: 'm6-w16-d106',
            dayNumber: 106,
            title: 'GitHub Actions CI Pipeline',
            duration: '75 min',
            objective: 'Run linting, TypeScript type-checking, and tests automatically on every PR.',
            learnItems: ['GitHub Actions syntax', 'Matrix testing', 'Caching node_modules and Docker layers'],
            buildItems: ['Write .github/workflows/ci.yml with test and typecheck gates'],
            completed: false,
            notes: '',
          },
          {
            id: 'm6-w16-weekend',
            dayNumber: 'Weekend',
            title: 'Automated CD Deployment Pipeline',
            duration: '3.0 hours',
            objective: 'Deploy live application upon git push to main branch with rollback capabilities.',
            learnItems: ['SSH deployment, zero-downtime container rolling restart'],
            buildItems: ['Write .github/workflows/deploy.yml and verify live deployment on push'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 7,
    title: 'Month 7: System Design & Scalability Architectures',
    subtitle: 'High-Level & Low-Level Architectural Mastery',
    objective: 'Design high-scale systems (URL Shortener, Real-time Chat, Food Delivery, E-Commerce).',
    weekdayTime: '75–90 min',
    weekendTime: '3.0 hours',
    weeks: [
      {
        weekNumber: 17,
        title: 'Week 17: URL Shortener & Scalability Fundamentals',
        focus: 'Capacity estimation, Base62 encoding, Redis caching, DB sharding',
        days: [
          {
            id: 'm7-w17-d113',
            dayNumber: 113,
            title: 'System Design Framework & Capacity Estimation',
            duration: '75 min',
            objective: 'Calculate QPS, Storage per year, Read/Write ratios, and Bandwidth.',
            learnItems: ['4-step System Design Framework', 'Back-of-the-envelope calculations'],
            buildItems: ['Calculate QPS and storage requirements for 100M daily active users'],
            completed: false,
            notes: '',
          },
          {
            id: 'm7-w17-weekend',
            dayNumber: 'Weekend',
            title: 'Design: URL Shortener (TinyURL)',
            duration: '3.0 hours',
            objective: 'Complete architecture diagram: Base62 hashing, collision handling, Redis cache, DB schema.',
            learnItems: ['Detailed architectural breakdown for URL Shortener'],
            buildItems: ['Draw end-to-end architecture diagram with failure scenarios'],
            completed: false,
            notes: '',
          },
        ],
      },
      {
        weekNumber: 18,
        title: 'Week 18: Real-Time Chat & Notification Systems',
        focus: 'WebSockets, Connection Servers, Redis Pub/Sub, Message Ordering',
        days: [
          {
            id: 'm7-w18-d120',
            dayNumber: 120,
            title: 'WebSockets & Connection Management at Scale',
            duration: '75 min',
            objective: 'WebSocket persistent connections, heartbeat pings, Redis Pub/Sub for cross-server delivery.',
            learnItems: ['WebSocket vs SSE vs Long Polling', 'Redis Pub/Sub adapter for distributed socket servers'],
            buildItems: ['Build prototype multi-server WebSocket chat with Redis Pub/Sub'],
            completed: false,
            notes: '',
          },
          {
            id: 'm7-w18-weekend',
            dayNumber: 'Weekend',
            title: 'Design: Scalable Chat System (WhatsApp / Slack)',
            duration: '3.0 hours',
            objective: 'Design message storage, read receipts, offline delivery, and presence status.',
            learnItems: ['Chat architecture design'],
            buildItems: ['Draft comprehensive system design document with data schemas and trade-offs'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 8,
    title: 'Month 8: Advanced Distributed Systems & Observability',
    subtitle: 'Event-Driven Microservices, Distributed Locks & Telemetry',
    objective: 'Transition from single-server mentality to distributed system principles.',
    weekdayTime: '75–90 min',
    weekendTime: '3.0 hours',
    weeks: [
      {
        weekNumber: 19,
        title: 'Week 19: Event-Driven Architecture & Message Brokers',
        focus: 'Eventual consistency, Kafka/RabbitMQ concepts, Saga pattern',
        days: [
          {
            id: 'm8-w19-d127',
            dayNumber: 127,
            title: 'Event-Driven Architectures vs Synchronous REST',
            duration: '75 min',
            objective: 'Decoupling services with events, publish-subscribe topology, and Saga pattern for distributed transactions.',
            learnItems: ['Synchronous coupling risks', 'Choreography vs Orchestration Sagas', 'Outbox pattern for guaranteed delivery'],
            buildItems: ['Implement Transactional Outbox pattern with PostgreSQL and background dispatcher'],
            completed: false,
            notes: '',
          },
          {
            id: 'm8-w19-weekend',
            dayNumber: 'Weekend',
            title: 'Distributed Locks with Redis (Redlock)',
            duration: '3.0 hours',
            objective: 'Prevent race conditions across multiple Node.js instances.',
            learnItems: ['Distributed locking principles and lease renewal'],
            buildItems: ['Implement Redlock distributed locking wrapper for critical financial/inventory actions'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 9,
    title: 'Month 9: AI Engineering Fundamentals & RAG',
    subtitle: 'LLMs, Embeddings, Vector Databases & Semantic Search',
    objective: 'Build semantic retrieval pipelines: User query -> Embedding -> Vector DB -> LLM Context -> Answer.',
    weekdayTime: '75–90 min',
    weekendTime: '3.0 hours',
    weeks: [
      {
        weekNumber: 20,
        title: 'Week 20: LLMs, Embeddings & Vector Stores (pgvector / Pinecone)',
        focus: 'Tokenization, context windows, vector embeddings, cosine similarity',
        days: [
          {
            id: 'm9-w20-d134',
            dayNumber: 134,
            title: 'LLM Mechanics & Vector Embeddings',
            duration: '75 min',
            objective: 'Understand token economics, embedding models (text-embedding-3-small), and vector geometry.',
            learnItems: ['Tokenization and context limits', 'Vector dimensions and cosine similarity', 'pgvector extension in PostgreSQL'],
            buildItems: ['Generate embeddings for project documentation using OpenAI / Gemini API and store in pgvector'],
            completed: false,
            notes: '',
          },
          {
            id: 'm9-w20-weekend',
            dayNumber: 'Weekend',
            title: 'Build Complete RAG Pipeline for Flagship Application',
            duration: '3.0 hours',
            objective: 'Implement Retrieval-Augmented Generation: query vector search + system prompt + streaming answer.',
            learnItems: ['RAG architecture and prompt injection defenses'],
            buildItems: ['Build working RAG endpoint with streaming response and source citations'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 10,
    title: 'Month 10: AI Agents, Function Calling & Tool Execution',
    subtitle: 'Autonomous AI Agents Operating On Database Systems',
    objective: 'Build an AI Agent that can query your database through controlled tools to answer complex user questions.',
    weekdayTime: '75–90 min',
    weekendTime: '3.0 hours',
    weeks: [
      {
        weekNumber: 21,
        title: 'Week 21: Tool Calling & Autonomous Agent Loop',
        focus: 'Structured outputs, JSON schema tool definitions, Multi-step reasoning',
        days: [
          {
            id: 'm10-w21-d141',
            dayNumber: 141,
            title: 'Function Calling & Tool Definitions',
            duration: '75 min',
            objective: 'Define type-safe JSON schemas for database tools that LLM can invoke.',
            learnItems: ['OpenAI / Gemini function calling protocols', 'Zod-to-JSONSchema conversion', 'Controlled tool execution'],
            buildItems: ['Create queryDatabase, searchProjects, getTaskStats tool definitions'],
            completed: false,
            notes: '',
          },
          {
            id: 'm10-w21-weekend',
            dayNumber: 'Weekend',
            title: 'Autonomous Database AI Agent Integration',
            duration: '3.0 hours',
            objective: 'Build agent: User asks "Which projects are delayed?" -> Agent executes SQL tool -> Analyzes -> Answers.',
            learnItems: ['Agent loops, guardrails, and error recovery'],
            buildItems: ['Integrate autonomous database AI agent with live chat UI in your project'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 11,
    title: 'Month 11: Flagship Project Polish & Interview Mock Drills',
    subtitle: 'Demonstrating Production Mastery & Deep Technical Articulation',
    objective: 'Master explaining every architectural decision, trade-off, index choice, and failure scenario.',
    weekdayTime: '75–90 min',
    weekendTime: '3.0 hours',
    weeks: [
      {
        weekNumber: 22,
        title: 'Week 22: Rigorous Mock Interviews & System Defense',
        focus: 'DSA practice (3-5 problems/week), System Design, Behavioral scenarios',
        days: [
          {
            id: 'm11-w22-d148',
            dayNumber: 148,
            title: 'Project Architecture Defense Drill',
            duration: '75 min',
            objective: 'Explain: Why PostgreSQL over MongoDB? Why Redis cache-aside? How does your async queue handle crashes?',
            learnItems: ['STAR method for technical storytelling', 'Defending engineering trade-offs under interview pressure'],
            buildItems: ['Record video/audio explaining your flagship architecture and review clarity'],
            completed: false,
            notes: '',
          },
          {
            id: 'm11-w22-weekend',
            dayNumber: 'Weekend',
            title: 'Full Technical Mock Interview Drill',
            duration: '3.0 hours',
            objective: 'Complete full mock interview: 1 DSA medium + 1 System Design + 1 Backend deep dive.',
            learnItems: ['Senior interview pacing and live problem solving'],
            buildItems: ['Score yourself on the Sunday Scoreboard across all 10 technical categories'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
  {
    monthNumber: 12,
    title: 'Month 12: High-Velocity Job Switch & 24 LPA Offers',
    subtitle: 'Targeted Applications, Recruiter Outreach & Negotiations',
    objective: 'Execute high-impact job switch strategy to secure ₹24 LPA+ Software Engineer package.',
    weekdayTime: '75–90 min',
    weekendTime: '3.0 hours',
    weeks: [
      {
        weekNumber: 23,
        title: 'Week 23: Application Sprint & Interview Rounds',
        focus: 'Direct referrals, recruiter outreach, live technical rounds, salary negotiation',
        days: [
          {
            id: 'm12-w23-d155',
            dayNumber: 155,
            title: 'Targeted Outreach & Referral Submissions',
            duration: '75 min',
            objective: 'Apply to top product startups and enterprise tech companies with customized evidence-based resumes.',
            learnItems: ['Cold outreach templates showcasing live projects and GitHub evidence'],
            buildItems: ['Send 10 targeted referral requests highlighting flagship full-stack & AI project'],
            completed: false,
            notes: '',
          },
          {
            id: 'm12-w23-weekend',
            dayNumber: 'Weekend',
            title: 'Live Interview Preparation & Offer Negotiation Strategy',
            duration: '3.0 hours',
            objective: 'Prepare negotiation scripts for competing offers and compensation packaging.',
            learnItems: ['Base vs ESOPs vs Bonus evaluation and counter-offer negotiation tactics'],
            buildItems: ['Finalize interview cheat-sheet and execute technical rounds'],
            completed: false,
            notes: '',
          },
        ],
      },
    ],
  },
];

export const INITIAL_SCOREBOARD = {
  typescript: 7,
  backend: 8,
  sql: 7,
  systemDesign: 5,
  cloud: 5,
  devOps: 5,
  aiEngineering: 6,
  frontend: 8,
  dsa: 6,
  communication: 8,
};
